export const ROUTES = {
  home: '/main',
  all: '*',
  single: ':id',
  details: 'details',
  category: 'category',
  payment: 'payment',
  paymentSuccess: '/payment-success',
  paymentSuccessV2: '/payment-success-v2',
  termsConditions: '/terms-n-conditions',
  result: 'result',
  search: 'search',
  rooms: 'rooms',
  booking: 'booking',
  notifications: 'notifications',
  reviews: '/reviews',
  passengers: 'passengers',
  faq: 'faq',
  travelDate: 'travel-date',
  list: 'list',
  special: 'special',
  selectPassengers: '/select-passengers',
  map: 'map',

  // PROFILE
  profile: '/profile',
  balance: 'balance',
  delete: 'delete',
  info: 'info',
  language: 'language',
  history: 'history',
  reforms: 'reforms',
  lawyers: 'lawyers',
  orders: 'orders',
  help: 'help',
  privacy: 'privacy-policy',

  // SERVICES
  services: '/services',
  tickets: 'tickets',
  tours: 'tours',
  hotTours: 'hot-tours',
  transfer: 'transfer',
  hotels: 'hotels',
  rental: 'car-rental',

  // AUTH
  sign: '/sign',
  verify: '/verify',
  welcome: '/welcome',
} as const;
